module Lol.Stats.Items where

import qualified Data.Map as M

import Lol.Items
import Lol.Stats.Types

cs :: CoreStats
cs = CoreStats 0 0 0 0.0 0 0 0.0 0 0 0

es :: ExtendedStats
es = ExtendedStats 0 0 0 0 0 0

-- Tables for item statistics. Not even close to ideal, but ATM I can't think
-- of a better way to do it.

-- | Table of item prices.
itemPrice :: M.Map Item Price
itemPrice = M.fromList [ (Empty, 0)
                       , (AbyssalScepter, 2650)
                       , (AegisOfTheLegion, 1925)
                       , (AmplifyingTome, 435)
                       , (ArchangelsStaff, 2855)
                       , (AtmasImpaler, 2355)
                       , (AvariceBlade, 750)
                       , (BFSword, 1650)
                       , (BansheesVeil, 2715)
                       , (BerserkersGreaves, 920)
                       , (BilgewaterCutlass, 1825)
                       , (BlastingWand, 860)
                       , (BootsOfMobility, 1000)
                       , (BootsOfSpeed, 300)
                       , (BootsOfSwiftness, 1000)
                       , (BrawlersGloves, 400)
                       , (CatalystTheProtector, 1325)
                       , (ChainVest, 700)
                       , (ChaliceOfHarmony, 890)
                       , (ClothArmor, 300)
                       , (CloakAndDagger, 1450)
                       , (CloakOfAgility, 830)
                       , (Dagger, 420)
                       , (DeathfireGrasp, 2610)
                       , (DoransBlade, 475)
                       , (DoransRing, 475)
                       , (DoransShield, 475)
                       , (EleisasMiracle, 1300)
                       , (EmblemOfValor, 800)
                       , (ExecutionersCalling, 1350)
                       , (FaerieCharm, 180)
                       , (FiendishCodex, 1245)
                       , (ForceOfNature, 2610)
                       , (FrozenHeart, 2775)
                       , (FrozenMallet, 3250)
                       , (GiantsBelt, 1110)
                       , (GlacialShroud, 1525)
                       , (GuardianAngel, 2600)
                       , (GuinsoosRageblade, 2235)
                       , (HauntingGuise, 1485)
                       , (HeartOfGold, 825)
                       , (Hexdrinker, 1800)
                       , (HextechGunblade, 3625)
                       , (HextechRevolver, 1200)
                       , (IonianBootsOfLucidity, 1050)
                       , (InfinityEdge, 3830)
                       , (KagesLuckyPick, 765)
                       , (Kindlegem, 850)
                       , (LastWhisper, 2290)
                       , (LichBane, 3470)
                       , (LongSword, 410)
                       , (Malady, 1825)
                       , (ManaManipulator, 475)
                       , (Manamune, 2110)
                       , (MekiPendant, 390)
                       , (MercurysTreads, 1200)
                       , (MoonflairSpellblade, 1200)
                       , (MorellosEvilTome, 2350)
                       , (NashorsTooth, 2885)
                       , (NeedlesslyLargeRod, 1600)
                       , (NegatronCloak, 740)
                       , (NinjaTabi, 850)
                       , (NullMagicMantle, 400)
                       , (Phage, 1315)
                       , (PhantomDancer, 2845)
                       , (PhilosophersStone, 800)
                       , (Pickaxe, 975)
                       , (QuicksilverSash, 1440)
                       , (RabadonsDeathcap, 3600)
                       , (RanduinsOmen, 3075)
                       , (RecurveBow, 1050)
                       , (RegrowthPendant, 435)
                       , (RejuvenationBead, 250)
                       , (RodOfAges, 3035)
                       , (RubyCrystal, 475)
                       , (RylaisCrystalScepter, 3105)
                       , (SapphireCrystal, 400)
                       , (Sheen, 1260)
                       , (ShurelyasReverie, 2200)
                       , (SorcerorsShoes, 1100)
                       , (SoulShroud, 2285)
                       , (SpiritVisage, 1550)
                       , (StarksFervor, 2550)
                       , (Stinger, 1140)
                       , (SunfireCape, 2610)
                       , (SwordOfTheDivine, 1970)
                       , (SwordOfTheOccult, 1369)
                       , (TearOfTheGoddess, 995)
                       , (Tiamat, 2070)
                       , (TheBlackCleaver, 2865)
                       , (TheBrutalizer, 1337)
                       , (Thornmail, 2000)
                       , (TrinityForce, 4070)
                       , (VampiricScepter, 450)
                       , (VoidStaff, 2295)
                       , (WardensMail, 1350)
                       , (WillOfTheAncients, 2100)
                       , (WitsEnd, 2000)
                       , (YoumuusGhostblade, 2687)
                       , (Zeal, 1195)
                       , (ZhonyasHourglass, 3100) ]

-- | Table of core item stats.
itemCoreStats :: M.Map Item CoreStats
itemCoreStats =
    M.fromList [ (AbyssalScepter, cs { _csMagicResist = 57 })
               , (AegisOfTheLegion,
                  cs { _csHealth = 270, _csArmor = 18, _csMagicResist = 24 })
               , (ArchangelsStaff, cs { _csMana = 400, _csManaRegen = 25 })
               , (AtmasImpaler, cs { _csArmor = 45 })
               , (BFSword, cs { _csAttackDamage = 45 })
               , (BansheesVeil,
                  cs { _csHealth = 375, _csMana = 375, _csMagicResist = 50 })
               , (BerserkersGreaves, cs { _csMovementSpeed = 70 })
               , (BilgewaterCutlass, cs { _csAttackDamage = 35 })
               , (BootsOfSpeed, cs { _csMovementSpeed = 50 })
               , (BootsOfMobility, cs { _csMovementSpeed = 70 })
               , (BootsOfSwiftness, cs { _csMovementSpeed = 90 })
               , (CatalystTheProtector, cs { _csHealth = 290, _csMana = 325 })
               , (ChainVest, cs { _csArmor = 45 })
               , (ChaliceOfHarmony, cs { _csManaRegen = 7.5, _csMagicResist = 30 })
               , (ClothArmor, cs { _csArmor = 18 })
               , (DeathfireGrasp, cs { _csManaRegen = 10 })
               , (DoransBlade, cs { _csHealth = 100, _csAttackDamage = 10 })
               , (DoransRing, cs { _csHealth = 100, _csManaRegen = 7 })
               , (DoransShield,
                  cs { _csHealth = 120 , _csHealthRegen = 120 , _csArmor = 10 })
               , (EleisasMiracle, cs { _csHealthRegen = 25, _csManaRegen = 20 })
               , (FaerieCharm, cs { _csManaRegen = 3 })
               , (FiendishCodex, cs { _csManaRegen = 7 })
               , (ForceOfNature, cs { _csHealthRegen = 40, _csMagicResist = 76 })
               , (FrozenHeart, cs { _csMana = 500, _csArmor = 99 })
               , (FrozenMallet, cs { _csHealth = 700, _csAttackDamage = 20 })
               , (GiantsBelt, cs { _csHealth = 430 })
               , (GlacialShroud, cs { _csMana = 425, _csArmor = 45 })
               , (GuardianAngel, cs { _csArmor = 68, _csMagicResist = 38 })
               , (GuinsoosRageblade, cs { _csAttackDamage = 35 })
               , (HauntingGuise, cs { _csHealth = 200 })
               , (HeartOfGold, cs { _csHealth = 250 })
               , (Hexdrinker, cs { _csAttackDamage = 35, _csMagicResist = 30 })
               , (HextechRevolver, cs { _csAttackDamage = 40 })
               , (IonianBootsOfLucidity, cs { _csMovementSpeed = 70 })
               , (InfinityEdge, cs { _csAttackDamage = 80 })
               , (Kindlegem, cs { _csHealth = 200 })
               , (LastWhisper, cs { _csAttackDamage = 40 })
               , (LichBane, cs { _csMana = 350, _csMagicResist = 30 })
               , (LongSword, cs { _csAttackDamage = 10 })
               , (ManaManipulator, cs { _csManaRegen = 7.2 })
               , (Manamune,
                  cs { _csMana = 350, _csAttackDamage = 20, _csManaRegen = 7 })
               , (MekiPendant, cs { _csManaRegen = 7 })
               , (MercurysTreads,
                  cs { _csMagicResist = 25, _csMovementSpeed = 70 })
               , (MorellosEvilTome, cs { _csManaRegen = 12 })
               , (NashorsTooth, cs { _csManaRegen = 10 })
               , (NegatronCloak, cs { _csMagicResist = 48 })
               , (NinjaTabi, cs { _csArmor = 25, _csMovementSpeed = 70 })
               , (NullMagicMantle, cs { _csMagicResist = 24 })
               , (Phage, cs { _csHealth = 225, _csAttackDamage = 18 })
               , (PhilosophersStone, cs { _csHealthRegen = 18, _csManaRegen = 8 })
               , (Pickaxe, cs { _csAttackDamage = 25 })
               , (QuicksilverSash, cs { _csMagicResist = 56 })
               , (RanduinsOmen,
                  cs { _csHealth = 350, _csHealthRegen = 25, _csArmor = 75 })
               , (RegrowthPendant, cs { _csHealthRegen = 15 })
               , (RejuvenationBead, cs { _csHealthRegen = 8 })
               , (RodOfAges, cs { _csHealth = 450, _csMana = 525 })
               , (RubyCrystal, cs { _csHealth = 180 })
               , (RylaisCrystalScepter, cs { _csHealth = 500 })
               , (SapphireCrystal, cs { _csMana = 200 })
               , (Sheen, cs { _csMana = 250 })
               , (ShurelyasReverie,
                 cs { _csHealth = 330, _csHealthRegen = 30, _csManaRegen = 15 })
               , (SorcerorsShoes, cs { _csMovementSpeed = 70 })
               , (SoulShroud, cs { _csHealth = 520 })
               , (SpiritVisage, cs { _csHealth = 250, _csMagicResist = 30 })
               , (SunfireCape, cs { _csHealth = 450, _csArmor = 45 })
               , (SwordOfTheOccult, cs { _csAttackDamage = 10 })
               , (TearOfTheGoddess, cs { _csMana = 350, _csManaRegen = 7 })
               , (TheBlackCleaver, cs { _csAttackDamage = 55 })
               , (TheBrutalizer, cs { _csAttackDamage = 25 })
               , (Thornmail, cs { _csArmor = 100 })
               , (Tiamat, cs { _csHealthRegen = 15
                             , _csManaRegen = 5
                             , _csAttackDamage = 50 })
               , (TrinityForce,
                  cs { _csHealth = 250, _csMana = 250, _csAttackDamage = 30 })
               , (WardensMail, cs { _csHealthRegen = 20, _csArmor = 50 })
               , (WitsEnd, cs { _csMagicResist = 30 })
               , (YoumuusGhostblade, cs { _csAttackDamage = 30 })
               , (ZhonyasHourglass, cs { _csArmor = 50 }) ]

-- | Table of extended item stats.
itemExtendedStats :: M.Map Item ExtendedStats
itemExtendedStats =
    M.fromList [ (AbyssalScepter, es { _esAbilityPower = 70 })
               , (AmplifyingTome, es { _esAbilityPower = 20 })
               , (ArchangelsStaff, es { _esAbilityPower = 45 })
               , (AtmasImpaler, es { _esCriticalChance = 18 })
               , (AvariceBlade, es { _esCriticalChance = 12 })
               , (BilgewaterCutlass, es { _esLifeSteal = 15 })
               , (BlastingWand, es { _esAbilityPower = 40 })
               , (BrawlersGloves, es { _esCriticalChance = 8 })
               , (CloakAndDagger, es { _esCriticalChance = 20 })
               , (CloakOfAgility, es { _esCriticalChance = 18 })
               , (DeathfireGrasp, es { _esAbilityPower = 60 })
               , (DoransBlade, es { _esLifeSteal = 3 })
               , (DoransRing, es { _esAbilityPower = 15 })
               , (EmblemOfValor, es { _esLifeSteal = 17 })
               , (ExecutionersCalling,
                  es { _esLifeSteal = 18, _esCriticalChance = 15 })
               , (FiendishCodex, es { _esAbilityPower = 30 })
               , (ForceOfNature, es { _esBonusMovementSpeed = 0.08 })
               , (GuinsoosRageblade, es { _esAbilityPower = 45 })
               , (HauntingGuise, es { _esAbilityPower = 25 })
               , (HextechGunblade,
                  es { _esAbilityPower = 70, _esLifeSteal = 15 })
               , (HextechRevolver, es { _esAbilityPower = 40 })
               , (InfinityEdge, es { _esCriticalChance = 25 })
               , (KagesLuckyPick, es { _esAbilityPower = 25 })
               , (LichBane,
                  es { _esAbilityPower = 80, _esBonusMovementSpeed = 0.07 })
               , (Malady, es { _esAbilityPower = 25 })
               , (MoonflairSpellblade, es { _esAbilityPower = 50 })
               , (MorellosEvilTome, es { _esAbilityPower = 75 })
               , (NeedlesslyLargeRod, es { _esAbilityPower = 80 })
               , (PhantomDancer,
                  es { _esCriticalChance = 30, _esBonusMovementSpeed = 0.15 })
               , (RabadonsDeathcap, es { _esAbilityPower = 140 })
               , (RodOfAges, es { _esAbilityPower = 60 })
               , (RylaisCrystalScepter, es { _esAbilityPower = 80 })
               , (Sheen, es { _esAbilityPower = 25 })
               , (TrinityForce, es { _esAbilityPower = 30
                                   , _esCriticalChance = 15
                                   , _esBonusMovementSpeed = 0.12 })
               , (VampiricScepter, es { _esLifeSteal = 12 })
               , (VoidStaff, es { _esAbilityPower = 70 })
               , (WillOfTheAncients, es { _esAbilityPower = 50 })
               , (YoumuusGhostblade, es { _esCriticalChance = 15 })
               , (Zeal,
                  es { _esCriticalChance = 10, _esBonusMovementSpeed = 0.08 })
               , (ZhonyasHourglass, es { _esAbilityPower = 100 }) ]
